### PR TITLE
テストを移植する:Service

### PR DESCRIPTION
**Pull request by hoand-vn**
## 概要(Overview・Refs Issue)
+ PullRequestの目的
  - phpUnit for Service

## 方針(Policy)
+ このPullRequestを作るにあたって考慮したものや除外し内容
  - Shopping feature

## 相談（Discussion）
+ 相談したいことや意見を求めたいこと
  - add service in service.yaml ( will be removed when have any code use them )
  - still not implement these functions: 
    - \Eccube\Tests\Service\ValidatableItemProcessorTest::testValidateCartFail
    - \Eccube\Tests\Service\PurchaseFlow\PurchaseFlowTest::testAddProcesser

### CODE REVIEW

**Comment by chihiro-adachi** [comment]
@hoand-vn 
> add service in service.yaml ( will be removed when have any code use them )
ok.

> still not implement these functions
ok. fixed and implemented by #2804 

please resolve comflict.

**Comment by hoand-vn** [comment]
@chihiro-adachi san, thank you and check them again, please

**Comment by chihiro-adachi** [comment]
@hoand-vn 
thanks, but travis-ci failed 😢

**Comment by hoand-vn** [comment]
@chihiro-adachi thank you :0 fixed it

**Comment by chihiro-adachi** [comment]
@hoand-vn thank you!

**Pull request merged**
